#!/bin/sh

if [ -z "${LAUREL_HOME}" ]
then
  echo "LAUREL_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${LAUREL_HOME}/lib" \
-m com.io7m.laurel.cmdline/com.io7m.laurel.cmdline.LCMain \
"$@"
